/**
 * Integration test for IndustryBillEmailModal search term filtering
 * Ensures search criteria is correctly passed to email sending functionality
 */

import React from 'react';
import { screen, waitFor, fireEvent } from '@testing-library/react';
import { render, createMockResponse } from '@utils/test-utils';
import { IndustryBillEmailModal } from '../IndustryBillEmailModal';
import { ElectricBillStatus, BillSource } from '@core/graphql/types';
import { INDUSTRY_BILLS_FOR_EMAIL } from '@core/graphql/queries/industryBillsForEmail';
import { gql } from '@apollo/client';

// GraphQL mutation for sending emails
const SEND_INDUSTRY_BILLS_EMAIL = gql`
  mutation SendIndustryBillsEmail($month: String!, $industryBillIds: [String!]) {
    sendIndustryBillsEmail(month: $month, industryBillIds: $industryBillIds) {
      success
      message
      batchId
      totalJobs
    }
  }
`;

// Mock data factory - creates realistic test data
const createMockIndustryBillsForEmail = (
  bills: Array<{
    id: string;
    name: string;
    status?: ElectricBillStatus;
    industryId?: string;
    industryName?: string;
  }>
) => {
  return bills.map((bill, i) => ({
    id: bill.id,
    status: bill.status || ElectricBillStatus.Approved,
    billSource: BillSource.AutoGenerated,
    hasOriginalFile: false,
    powerPlantName: bill.name,
    powerPlantNumber: `E${(i + 1).toString().padStart(6, '0')}`,
    industry: {
      id: bill.industryId || `industry-${i + 1}`,
      name: bill.industryName || `發電業 ${i + 1}`,
    },
  }));
};

describe('IndustryBillEmailModal Search Filtering', () => {
  const baseProps = {
    open: true,
    onClose: jest.fn(),
    month: '2024-11',
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Query with search term', () => {
    it('should pass term parameter to GraphQL query when provided', async () => {
      // Arrange: Mock response for query with term
      const filteredBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠A' },
        { id: 'bill-2', name: '太陽能電廠B' },
      ]);

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '太陽能' },
          { industryBillsForEmail: filteredBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="太陽能" />, { mocks });

      // Assert: Should display filtered bills count
      await waitFor(() => {
        expect(screen.getByText(/將發送 2 封郵件，共 2 筆電費單/)).toBeInTheDocument();
      });

      // Assert: Filtered bills should be visible in preview
      expect(screen.getByText('太陽能電廠A')).toBeInTheDocument();
      expect(screen.getByText('太陽能電廠B')).toBeInTheDocument();
    });

    it('should query all bills when term is not provided', async () => {
      // Arrange: Mock response for query without term
      const allBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠A' },
        { id: 'bill-2', name: '太陽能電廠B' },
        { id: 'bill-3', name: '風力電廠C' },
      ]);

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: undefined },
          { industryBillsForEmail: allBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} />, { mocks });

      // Assert: Should display all bills count
      await waitFor(() => {
        expect(screen.getByText(/將發送 3 封郵件，共 3 筆電費單/)).toBeInTheDocument();
      });
    });

    it('should query all bills when term is empty string', async () => {
      // Arrange: Mock response for empty term (should be treated as no filter)
      const allBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠A' },
        { id: 'bill-2', name: '風力電廠B' },
      ]);

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '' },
          { industryBillsForEmail: allBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="" />, { mocks });

      // Assert: Should display all bills
      await waitFor(() => {
        expect(screen.getByText(/將發送 2 封郵件，共 2 筆電費單/)).toBeInTheDocument();
      });
    });
  });

  describe('Empty search results', () => {
    it('should show empty state when search term matches no bills', async () => {
      // Arrange: Mock empty response
      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '不存在的關鍵字' },
          { industryBillsForEmail: [] }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="不存在的關鍵字" />, { mocks });

      // Assert: Should show no eligible bills message
      await waitFor(() => {
        expect(screen.getByText('無符合條件的電費單可寄送')).toBeInTheDocument();
      });

      // Assert: Send button should not be shown
      expect(screen.queryByRole('button', { name: /確認寄信/i })).not.toBeInTheDocument();
    });
  });

  describe('Send mutation with filtered results', () => {
    it('should send only filtered bill IDs when search term is provided', async () => {
      // Arrange: Only 2 bills match the search
      const filteredBills = createMockIndustryBillsForEmail([
        { id: 'specific-bill-1', name: '太陽能電廠A', industryId: 'ind-1', industryName: '公司A' },
        { id: 'specific-bill-2', name: '太陽能電廠B', industryId: 'ind-2', industryName: '公司B' },
      ]);

      const queryMock = createMockResponse(
        INDUSTRY_BILLS_FOR_EMAIL,
        { month: '2024-11', term: '太陽能' },
        { industryBillsForEmail: filteredBills }
      );

      // Mutation should receive only the filtered bill IDs
      const mutationMock = createMockResponse(
        SEND_INDUSTRY_BILLS_EMAIL,
        { month: '2024-11', industryBillIds: ['specific-bill-1', 'specific-bill-2'] },
        {
          sendIndustryBillsEmail: {
            success: true,
            message: '已發送 2 封郵件',
            batchId: 'batch-123',
            totalJobs: 2,
          },
        }
      );

      // Act
      render(
        <IndustryBillEmailModal {...baseProps} term="太陽能" />,
        { mocks: [queryMock, mutationMock] }
      );

      // Wait for bills to load
      await waitFor(() => {
        expect(screen.getByText(/將發送 2 封郵件，共 2 筆電費單/)).toBeInTheDocument();
      });

      // Act: Click send button
      const sendButton = screen.getByRole('button', { name: /確認寄信/i });
      fireEvent.click(sendButton);

      // Assert: Modal should close on success
      await waitFor(() => {
        expect(baseProps.onClose).toHaveBeenCalled();
      });
    });

    it('should send all bill IDs when no search term is provided', async () => {
      // Arrange: All 3 bills
      const allBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠A', industryId: 'ind-1' },
        { id: 'bill-2', name: '太陽能電廠B', industryId: 'ind-2' },
        { id: 'bill-3', name: '風力電廠C', industryId: 'ind-3' },
      ]);

      const queryMock = createMockResponse(
        INDUSTRY_BILLS_FOR_EMAIL,
        { month: '2024-11', term: undefined },
        { industryBillsForEmail: allBills }
      );

      // Mutation should receive all bill IDs
      const mutationMock = createMockResponse(
        SEND_INDUSTRY_BILLS_EMAIL,
        { month: '2024-11', industryBillIds: ['bill-1', 'bill-2', 'bill-3'] },
        {
          sendIndustryBillsEmail: {
            success: true,
            message: '已發送 3 封郵件',
            batchId: 'batch-456',
            totalJobs: 3,
          },
        }
      );

      // Act
      render(
        <IndustryBillEmailModal {...baseProps} />,
        { mocks: [queryMock, mutationMock] }
      );

      // Wait for bills to load
      await waitFor(() => {
        expect(screen.getByText(/將發送 3 封郵件，共 3 筆電費單/)).toBeInTheDocument();
      });

      // Act: Click send button
      const sendButton = screen.getByRole('button', { name: /確認寄信/i });
      fireEvent.click(sendButton);

      // Assert: Modal should close on success
      await waitFor(() => {
        expect(baseProps.onClose).toHaveBeenCalled();
      });
    });
  });

  describe('UI display with search term', () => {
    it('should show correct bill count matching search criteria', async () => {
      // Arrange: 2 bills match search, others don't (but we only get filtered results)
      const filteredBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠松山' },
        { id: 'bill-2', name: '太陽能電廠大安' },
      ]);

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '太陽能' },
          { industryBillsForEmail: filteredBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="太陽能" />, { mocks });

      // Assert: Should show filtered count
      await waitFor(() => {
        expect(screen.getByText(/將發送 2 封郵件，共 2 筆電費單/)).toBeInTheDocument();
      });

      // Assert: Preview should show filtered bills
      expect(screen.getByText('太陽能電廠松山')).toBeInTheDocument();
      expect(screen.getByText('太陽能電廠大安')).toBeInTheDocument();
    });

    it('should group bills by industry correctly when filtered', async () => {
      // Arrange: 3 bills from 2 industries
      const filteredBills = createMockIndustryBillsForEmail([
        { id: 'bill-1', name: '太陽能電廠A-1', industryId: 'ind-A', industryName: '發電公司A' },
        { id: 'bill-2', name: '太陽能電廠A-2', industryId: 'ind-A', industryName: '發電公司A' },
        { id: 'bill-3', name: '太陽能電廠B-1', industryId: 'ind-B', industryName: '發電公司B' },
      ]);

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '太陽能' },
          { industryBillsForEmail: filteredBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="太陽能" />, { mocks });

      // Assert: Should show 2 emails (one per industry) for 3 bills
      await waitFor(() => {
        expect(screen.getByText(/將發送 2 封郵件，共 3 筆電費單/)).toBeInTheDocument();
      });
    });
  });

  describe('Status filtering with search', () => {
    it('should filter by status AND search term (only show approved in eligible)', async () => {
      // Arrange: Mix of approved and pending bills
      const mixedBills = [
        ...createMockIndustryBillsForEmail([
          { id: 'bill-1', name: '太陽能電廠A', status: ElectricBillStatus.Approved },
          { id: 'bill-2', name: '太陽能電廠B', status: ElectricBillStatus.Pending },
        ]),
      ];

      const mocks = [
        createMockResponse(
          INDUSTRY_BILLS_FOR_EMAIL,
          { month: '2024-11', term: '太陽能' },
          { industryBillsForEmail: mixedBills }
        ),
      ];

      // Act
      render(<IndustryBillEmailModal {...baseProps} term="太陽能" />, { mocks });

      // Assert: Should show only 1 eligible bill (the approved one)
      await waitFor(() => {
        expect(screen.getByText(/將發送 1 封郵件，共 1 筆電費單/)).toBeInTheDocument();
      });

      // Assert: Should show warning about unapproved bills
      expect(screen.getByText(/待處理電費單清單/)).toBeInTheDocument();
    });
  });
});
