import { Autocomplete, TextField, Box, Button, Chip } from '@mui/material';
import { ElectricBillStatus, BillSource } from '@core/graphql/types';
import ClearIcon from '@mui/icons-material/Clear';

// 狀態選項配置
const STATUS_OPTIONS = [
  { value: ElectricBillStatus.Pending, label: '待審核' },
  { value: ElectricBillStatus.Approved, label: '已審核' },
  { value: ElectricBillStatus.Draft, label: '草稿' },
  { value: ElectricBillStatus.Rejected, label: '已拒絕' },
];

// 來源選項配置
const BILL_SOURCE_OPTIONS = [
  { value: BillSource.AutoGenerated, label: '自動生成' },
  { value: BillSource.ManualImport, label: '手動匯入' },
];

interface BillFiltersProps {
  statuses: ElectricBillStatus[];
  billSources: BillSource[];
  onStatusChange: (statuses: ElectricBillStatus[]) => void;
  onBillSourceChange: (sources: BillSource[]) => void;
  onClear: () => void;
}

export function BillFilters({
  statuses,
  billSources,
  onStatusChange,
  onBillSourceChange,
  onClear,
}: BillFiltersProps) {
  const hasFilters = statuses.length > 0 || billSources.length > 0;

  return (
    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, flexWrap: 'wrap' }}>
      {/* 狀態篩選 */}
      <Autocomplete
        multiple
        size="small"
        options={STATUS_OPTIONS}
        getOptionLabel={(option) => option.label}
        value={STATUS_OPTIONS.filter((opt) => statuses.includes(opt.value))}
        onChange={(_, newValue) => {
          onStatusChange(newValue.map((v) => v.value));
        }}
        renderInput={(params) => (
          <TextField {...params} label="狀態" placeholder={statuses.length === 0 ? '全部' : ''} />
        )}
        renderTags={(value, getTagProps) =>
          value.map((option, index) => (
            <Chip
              {...getTagProps({ index })}
              key={option.value}
              label={option.label}
              size="small"
            />
          ))
        }
        sx={{ minWidth: 200 }}
        isOptionEqualToValue={(option, value) => option.value === value.value}
      />

      {/* 來源篩選 */}
      <Autocomplete
        multiple
        size="small"
        options={BILL_SOURCE_OPTIONS}
        getOptionLabel={(option) => option.label}
        value={BILL_SOURCE_OPTIONS.filter((opt) => billSources.includes(opt.value))}
        onChange={(_, newValue) => {
          onBillSourceChange(newValue.map((v) => v.value));
        }}
        renderInput={(params) => (
          <TextField {...params} label="來源" placeholder={billSources.length === 0 ? '全部' : ''} />
        )}
        renderTags={(value, getTagProps) =>
          value.map((option, index) => (
            <Chip
              {...getTagProps({ index })}
              key={option.value}
              label={option.label}
              size="small"
            />
          ))
        }
        sx={{ minWidth: 180 }}
        isOptionEqualToValue={(option, value) => option.value === value.value}
      />

      {/* 清除篩選按鈕 */}
      {hasFilters && (
        <Button
          size="small"
          startIcon={<ClearIcon />}
          onClick={onClear}
          color="inherit"
        >
          清除篩選
        </Button>
      )}
    </Box>
  );
}
